service: ven-sls-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-southeast-1
  httpApi:
    cors: true

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-offline
