service: ven-sls-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-offline
